# Generated by Django 3.1.3 on 2021-01-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover', models.URLField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CartoonSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('season_cover', models.URLField(blank=True, max_length=300, null=True)),
                ('season_name', models.CharField(blank=True, max_length=200, null=True)),
                ('season_description', models.TextField(blank=True)),
                ('cartoon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cartoon')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cover', models.URLField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('published', models.DateField(auto_now_add=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cartoonseason')),
            ],
        ),
    ]
